- id: sqlfluff-conda
  name: sqlfluff-conda
  # Needs to use "--force" to disable confirmation
  # By default all the rules are applied
  entry: sqlfluff fix --force
  language: conda
  description: "Fixes sql lint errors with `SQLFluff`"
  types: [sql]
  require_serial: true
  additional_dependencies: []
- id: sqlfluff-conda-lint
  name: sqlfluff-conda
  entry: sqlfluff lint
  language: conda
  description: "Lints sql files with `SQLFluff`"
  types: [sql]
  require_serial: true
  additional_dependencies: []
