- id: sqlfluff-lint-conda
  name: sqlfluff-lint-conda
  entry: sqlfluff lint
  language: conda
  description: 'Lints sql files with `SQLFluff`'
  types: [sql]
  require_serial: true
  additional_dependencies: []
- id: sqlfluff-fix-conda
  name: sqlfluff-fix-conda
  # Needs to use "--force" to disable confirmation
  # By default all the rules are applied
  entry: sqlfluff fix --force
  language: conda
  description: 'Fixes sql lint errors with `SQLFluff`'
  types: [sql]
  require_serial: true
  additional_dependencies: []
