- id: sqlfluff-conda
  name: sqlfluff-conda
  description: 'Fixes sql lint errors with `SQLFluff`'
  # By default all the rules are applied
  entry: sqlfluff fix --show-lint-violations --processes 0
  language: conda
  types: [sql]
  require_serial: true
- id: sqlfluff-conda-lint
  name: sqlfluff-conda
  entry: sqlfluff lint --processes 0
  language: conda
  description: 'Lints sql files with `SQLFluff`'
  types: [sql]
  require_serial: true
